# 🤖 AI Functions Showcase - The Art of the Possible

**COMPREHENSIVE AI DEMONSTRATION** - Run this after notebook 01.

## What this notebook demonstrates:
- ✅ **ai_classify** - Intelligent priority and category classification
- ✅ **ai_extract** - Structured data extraction from unstructured text  
- ✅ **ai_gen** - Complex analysis, summaries, and creative content generation
- ✅ **Final Summary Table** - Complete AI-powered ticket analysis

**Prerequisites:** Run `01_sample_data_generation.ipynb` first

## AI Functions Showcase:
- `ai_classify` - For priority and category classification
- `ai_extract` - For structured data extraction  
- `ai_gen` - For complex analysis and summaries

---

## 🎯 Goal: Demonstrate the full power of Databricks AI Functions

In [1]:
# Import required libraries
from pyspark.sql.functions import *
from pyspark.sql.types import *
import json
from datetime import datetime

# Import configuration
%run ./config

print("✅ Libraries imported and configuration loaded")
print(f"🎯 Using Unity Catalog: {UNITY_CATALOG['catalog_name']}.{UNITY_CATALOG['schema_name']}")
print("🚀 Ready to showcase Databricks AI Functions!")

✅ Libraries imported and configuration loaded
🎯 Using Unity Catalog: quickstart_catalog_vkm_external.classify_tickets
🚀 Ready to showcase Databricks AI Functions!

In [2]:
# Load Sample Data
print("📊 Loading sample ticket data from Unity Catalog...")

# Load the sample ticket data from Unity Catalog
df_tickets = spark.table(TABLES["raw_tickets"])
print(f"✅ Loaded {df_tickets.count()} tickets from: {TABLES['raw_tickets']}")

# Display sample data
print("\n📋 Sample ticket data:")
display(df_tickets.select("ticket_id", "short_description", "description").limit(3))

📊 Loading sample ticket data from Unity Catalog...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Loaded 10 tickets from: quickstart_catalog_vkm_external.classify_tickets.raw_tickets

📋 Sample ticket data:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, description: string]

# 🎯 AI Function #1: ai_classify

**Purpose:** Intelligent classification of text into predefined categories

**Use Cases:** Priority classification, category assignment, sentiment analysis, risk assessment

**Example:** Classify ticket priorities based on description content

In [3]:
# AI Function #1: ai_classify - Priority Classification
print("🎯 Demonstrating ai_classify for priority classification...")

# Register DataFrame as temporary view for SQL access
df_tickets.createOrReplaceTempView("tickets")

# Use ai_classify to classify ticket priorities
df_with_priority = spark.sql("""
    SELECT
        *,
        ai_classify(
            description, 
            ARRAY('Low Priority', 'Medium Priority', 'High Priority', 'Urgent Priority')
        ) as ai_priority_classification
    FROM tickets
""")

print("✅ ai_classify completed - Priority classification done!")
print("\n📊 Priority Classification Results:")
display(df_with_priority.select("ticket_id", "short_description", "ai_priority_classification").limit(5))

# Show distribution of AI classifications
print("\n📈 Priority Distribution:")
df_with_priority.groupBy("ai_priority_classification").count().orderBy(desc("count")).show()

🎯 Demonstrating ai_classify for priority classification...
✅ ai_classify completed - Priority classification done!

📊 Priority Classification Results:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, ai_priority_classification: string]

📈 Priority Distribution:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------------------------+-----+
|ai_priority_classification|count|
+--------------------------+-----+
|           Urgent Priority|    6|
|             High Priority|    3|
|           Medium Priority|    1|
+--------------------------+-----+

# 🎯 AI Function #2: ai_extract

**Purpose:** Extract structured data from unstructured text using schema definition

**Use Cases:** Action items extraction, contact information parsing, date/time extraction, entity recognition

**Example:** Extract specific action items and requirements from ticket descriptions

In [ ]:
# AI Function #2: ai_extract - Action Items Extraction
print("🎯 Demonstrating ai_extract for structured data extraction...")

# Register DataFrame as temporary view for SQL access
df_with_priority.createOrReplaceTempView("tickets_with_priority")

# Use ai_extract with proper ARRAY syntax for schema
df_with_extraction = spark.sql("""
    SELECT
        *,
        ai_extract(
            description,
            ARRAY(
                STRUCT('action_items' AS key, 'array<string>' AS value),
                STRUCT('main_requirement' AS key, 'string' AS value),
                STRUCT('urgency_level' AS key, 'string' AS value),
                STRUCT('affected_systems' AS key, 'array<string>' AS value)
            )
        ) as ai_extracted_data
    FROM tickets_with_priority
""")

print("✅ ai_extract completed - Structured data extraction done!")
print("\n📊 Extraction Results:")
display(df_with_extraction.select("ticket_id", "short_description", "ai_extracted_data").limit(3))

# Parse the extracted data for better display
df_parsed = df_with_extraction.withColumn(
    "action_items", 
    col("ai_extracted_data.action_items")
).withColumn(
    "main_requirement", 
    col("ai_extracted_data.main_requirement")
).withColumn(
    "urgency_level", 
    col("ai_extracted_data.urgency_level")
).withColumn(
    "affected_systems", 
    col("ai_extracted_data.affected_systems")
)

print("\n📋 Parsed Extraction Results:")
display(df_parsed.select("ticket_id", "action_items", "main_requirement", "urgency_level").limit(3))

🎯 Demonstrating ai_extract for structured data extraction...

{"ts": "2025-09-19 20:53:34.481", "level": "ERROR", "logger": "SQLQueryContextLogger", "msg": "[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve \"ai_extract(description, {\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"})\" due to data type mismatch: The second parameter requires the \"ARRAY\" type, however \"{\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"}\" has the type \"STRING\". SQLSTATE: 42K09; line 4 pos 8;\n'Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202, ai_extract(description#114164, {\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"}) AS ai_extracted_data#114246]\n+- SubqueryAlias tickets_with_priority\n   +- View (`tickets_with_priority`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202])\n      +- Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_classify(description#114164, array(Low Priority, Medium Priority, High Priority, Urgent Priority)) AS ai_priority_classification#114202]\n         +- SubqueryAlias tickets\n            +- View (`tickets`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169])\n               +- SubqueryAlias quickstart_catalog_vkm_external.classify_tickets.raw_tickets\n                  +- Relation quickstart_catalog_vkm_external.classify_tickets.raw_tickets[assigned_to#114162,assignment_group#114163,description#114164,priority#114165,requested_by#114166,short_description#114167,state#114168,ticket_id#114169] parquet\n\n\nJVM stacktrace:\norg.apache.spark.sql.catalyst.ExtendedAnalysisException\n\tat org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:80)\n\tat org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:73)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10(CheckAnalysis.scala:506)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10$adapted(CheckAnalysis.scala:474)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:303)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:302)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:302)\n\tat scala.collection.immutable.Vector.foreach(Vector.scala:1895)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:302)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$9(CheckAnalysis.scala:474)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$9$adapted(CheckAnalysis.scala:474)\n\tat scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)\n\tat scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)\n\tat scala.collection.AbstractIterable.foreach(Iterable.scala:933)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:474)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:307)\n\tat org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:303)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:307)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:278)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:425)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:263)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:250)\n\tat org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:250)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:425)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:254)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:233)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:254)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:96)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:131)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:87)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:487)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:425)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:487)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$3(QueryExecution.scala:308)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:562)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$6(QueryExecution.scala:703)\n\tat org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:152)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:703)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1342)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:696)\n\tat com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:692)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:692)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:295)\n\tat com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:80)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:294)\n\tat scala.util.Try$.apply(Try.scala:210)\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:58)\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:340)\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:274)\n\tat org.apache.spark.sql.Dataset$.$anonfun$ofRows$3(Dataset.scala:149)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1470)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1470)\n\tat org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:141)\n\tat org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:1143)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.SparkSession.sql(SparkSession.scala:1095)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:3606)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:3435)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3370)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:413)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:312)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:233)\n\tat org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:464)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:464)\n\tat org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)\n\tat org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:90)\n\tat org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:241)\n\tat org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:89)\n\tat org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:463)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:233)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:614)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)\n\tat com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)\n\tat com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)\n\tat scala.util.Using$.resource(Using.scala:261)\n\tat com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:614)", "context": {"errorClass": "DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE"}, "exception": {"class": "_MultiThreadedRendezvous", "msg": "<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.INTERNAL\n\tdetails = \"[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve \"ai_extract(description, {\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"})\" due to data type mismatch: The second parameter requires the \"ARRAY\" type, however \"{\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"}\" has the type \"STRING\". SQLSTATE: 42K09; line 4 pos 8;\n'Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202, ai_extract(description#114164, {\"action_items\": \"array<string>\", \"main_requirement\": \"string\", \"urgency_level\": \"string\", \"affected_systems\": \"array<string>\"}) AS ai_extracted_data#114246]\n+- SubqueryAlias tickets_with_priority\n   +- View (`tickets_with_priority`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202])\n      +- Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_classify(description#114164, array(Low Priority, Medium Priority, High Priority, Urgent Priority)) AS ai_priority_classification#114202]\n         +- SubqueryAlias tickets\n            +- View (`tickets`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169])\n               +- SubqueryAlias quickstart_catalog_vkm_external.classify_tickets.raw_tickets\n                  +- Relation quickstart_catalog_vkm_external.classify_tickets.raw_tickets[assigned_to#114162,assignment_group#114163,description#114164,priority#114165,requested_by#114166,short_description#114167,state#114168,ticket_id#114169] parquet\n\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2025-09-19T20:53:34.304214-04:00\", grpc_status:13, grpc_message:\"[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve \\\"ai_extract(description, {\\\"action_items\\\": \\\"array<string>\\\", \\\"main_requirement\\\": \\\"string\\\", \\\"urgency_level\\\": \\\"string\\\", \\\"affected_systems\\\": \\\"array<string>\\\"})\\\" due to data type mismatch: The second parameter requires the \\\"ARRAY\\\" type, however \\\"{\\\"action_items\\\": \\\"array<string>\\\", \\\"main_requirement\\\": \\\"string\\\", \\\"urgency_level\\\": \\\"string\\\", \\\"affected_systems\\\": \\\"array<string>\\\"}\\\" has the type \\\"STRING\\\". SQLSTATE: 42K09; line 4 pos 8;\\n\\'Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202, ai_extract(description#114164, {\\\"action_items\\\": \\\"array<string>\\\", \\\"main_requirement\\\": \\\"string\\\", \\\"urgency_level\\\": \\\"string\\\", \\\"affected_systems\\\": \\\"array<string>\\\"}) AS ai_extracted_data#114246]\\n+- SubqueryAlias tickets_with_priority\\n   +- View (`tickets_with_priority`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202])\\n      +- Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_classify(description#114164, array(Low Priority, Medium Priority, High Priority, Urgent Priority)) AS ai_priority_classification#114202]\\n         +- SubqueryAlias tickets\\n            +- View (`tickets`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169])\\n               +- SubqueryAlias quickstart_catalog_vkm_external.classify_tickets.raw_tickets\\n                  +- Relation quickstart_catalog_vkm_external.classify_tickets.raw_tickets[assigned_to#114162,assignment_group#114163,description#114164,priority#114165,requested_by#114166,short_description#114167,state#114168,ticket_id#114169] parquet\\n\"}\"\n>", "stacktrace": [{"class": null, "method": "_execute_and_fetch_as_iterator", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py", "line": "1932"}, {"class": null, "method": "__next__", "file": "<frozen _collections_abc>", "line": "356"}, {"class": null, "method": "send", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "141"}, {"class": null, "method": "_has_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "202"}, {"class": null, "method": "_has_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "174"}, {"class": null, "method": "_call_iter", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "307"}, {"class": null, "method": "_call_iter", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "279"}, {"class": null, "method": "<lambda>", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "175"}, {"class": null, "method": "__iter__", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py", "line": "658"}, {"class": null, "method": "__next__", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/grpc/_channel.py", "line": "543"}, {"class": null, "method": "_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/grpc/_channel.py", "line": "969"}]}}
ERROR:SQLQueryContextLogger:[DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "ai_extract(description, {"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"})" due to data type mismatch: The second parameter requires the "ARRAY" type, however "{"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"}" has the type "STRING". SQLSTATE: 42K09; line 4 pos 8;
'Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202, ai_extract(description#114164, {"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"}) AS ai_extracted_data#114246]
+- SubqueryAlias tickets_with_priority
   +- View (`tickets_with_priority`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202])
      +- Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_classify(description#114164, array(Low Priority, Medium Priority, High Priority, Urgent Priority)) AS ai_priority_classification#114202]
         +- SubqueryAlias tickets
            +- View (`tickets`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169])
               +- SubqueryAlias quickstart_catalog_vkm_external.classify_tickets.raw_tickets
                  +- Relation quickstart_catalog_vkm_external.classify_tickets.raw_tickets[assigned_to#114162,assignment_group#114163,description#114164,priority#114165,requested_by#114166,short_description#114167,state#114168,ticket_id#114169] parquet


JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:80)
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:73)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10(CheckAnalysis.scala:506)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10$adapted(CheckAnalysis.scala:474)

AnalysisException: [DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "ai_extract(description, {"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"})" due to data type mismatch: The second parameter requires the "ARRAY" type, however "{"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"}" has the type "STRING". SQLSTATE: 42K09; line 4 pos 8;
'Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202, ai_extract(description#114164, {"action_items": "array<string>", "main_requirement": "string", "urgency_level": "string", "affected_systems": "array<string>"}) AS ai_extracted_data#114246]
+- SubqueryAlias tickets_with_priority
   +- View (`tickets_with_priority`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_priority_classification#114202])
      +- Project [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169, ai_classify(description#114164, array(Low Priority, Medium Priority, High Priority, Urgent Priority)) AS ai_priority_classification#114202]
         +- SubqueryAlias tickets
            +- View (`tickets`, [assigned_to#114162, assignment_group#114163, description#114164, priority#114165, requested_by#114166, short_description#114167, state#114168, ticket_id#114169])
               +- SubqueryAlias quickstart_catalog_vkm_external.classify_tickets.raw_tickets
                  +- Relation quickstart_catalog_vkm_external.classify_tickets.raw_tickets[assigned_to#114162,assignment_group#114163,description#114164,priority#114165,requested_by#114166,short_description#114167,state#114168,ticket_id#114169] parquet


JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:80)
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:73)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10(CheckAnalysis.scala:506)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$10$adapted(CheckAnalysis.scala:474)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:303)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:302)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:302)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1895)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:302)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$9(CheckAnalysis.scala:474)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$9$adapted(CheckAnalysis.scala:474)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2(CheckAnalysis.scala:474)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$2$adapted(CheckAnalysis.scala:307)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:303)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0(CheckAnalysis.scala:307)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis0$(CheckAnalysis.scala:278)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis0(Analyzer.scala:425)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:263)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:250)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:250)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:425)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$resolveInFixedPoint$1(HybridAnalyzer.scala:254)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:233)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:254)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:96)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:131)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:87)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:487)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:425)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:487)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$3(QueryExecution.scala:308)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:562)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$6(QueryExecution.scala:703)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:152)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:703)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1342)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:696)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:692)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:692)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:295)
	at com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:294)
	at scala.util.Try$.apply(Try.scala:210)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:340)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:274)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$3(Dataset.scala:149)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1470)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1470)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:141)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:1143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:1095)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:3606)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:3435)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3370)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:413)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:312)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:233)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:464)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:464)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:90)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:241)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:89)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:463)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:233)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:614)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)
	at scala.util.Using$.resource(Using.scala:261)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:614)

# 🎯 AI Function #3: ai_gen

**Purpose:** Generate creative content, summaries, and complex analysis

**Use Cases:** Executive summaries, detailed analysis, creative content, recommendations

**Example:** Generate comprehensive ticket analysis and recommendations

In [ ]:
# AI Function #3: ai_gen - Comprehensive Analysis
print("🎯 Demonstrating ai_gen for comprehensive analysis...")

# Register DataFrame as temporary view for SQL access
df_parsed.createOrReplaceTempView("tickets_with_extraction")

# Use ai_gen to create comprehensive analysis
df_with_analysis = spark.sql("""
    SELECT
        *,
        ai_gen(
            CONCAT(
                'Analyze this IT ticket and provide: ',
                '1. Executive summary (2-3 sentences), ',
                '2. Technical complexity (Low/Medium/High), ',
                '3. Estimated effort (hours), ',
                '4. Risk assessment (Low/Medium/High), ',
                '5. Recommended next steps. ',
                'Ticket: ', short_description, ' - ', description
            )
        ) as ai_comprehensive_analysis
    FROM tickets_with_extraction
""")

print("✅ ai_gen completed - Comprehensive analysis done!")
print("\n📊 Analysis Results:")
display(df_with_analysis.select("ticket_id", "short_description", "ai_comprehensive_analysis").limit(3))

# 🎉 Final Summary Table - The Art of the Possible

**Complete AI-powered ticket analysis showcasing all three AI functions**

In [ ]:
# Create Final Summary Table
print("🎉 Creating comprehensive summary table...")

# Create a clean summary table with all AI results
df_final_summary = df_with_analysis.select(
    "ticket_id",
    "short_description",
    "ai_priority_classification",
    "action_items",
    "main_requirement", 
    "urgency_level",
    "affected_systems",
    "ai_comprehensive_analysis"
).withColumn(
    "ai_showcase_timestamp", 
    current_timestamp()
)

print("✅ Final summary table created!")
print(f"📊 Total tickets analyzed: {df_final_summary.count()}")

# Display the comprehensive results
print("\n🎯 COMPLETE AI SHOWCASE RESULTS:")
print("="*80)
display(df_final_summary.limit(5))

# Save to Unity Catalog
print("\n💾 Saving results to Unity Catalog...")
df_final_summary.write.format("delta").mode("overwrite").saveAsTable(TABLES["ai_showcase_results"])
print(f"✅ Results saved to: {TABLES['ai_showcase_results']}")

# Show summary statistics
print("\n📈 AI Showcase Summary Statistics:")
print(f"🎯 Tickets processed: {df_final_summary.count()}")
print(f"🤖 AI functions demonstrated: 3 (ai_classify, ai_extract, ai_gen)")
print(f"📊 Data saved to Unity Catalog: {TABLES['ai_showcase_results']}")

print("\n" + "="*80)
print("🎉 AI SHOWCASE COMPLETED SUCCESSFULLY!")
print("="*80)
print("✅ ai_classify: Priority classification")
print("✅ ai_extract: Structured data extraction") 
print("✅ ai_gen: Comprehensive analysis")
print("✅ Final summary table created and saved")
print("="*80)