# 🔍 02 - AI-Powered Action Extraction

**COMPLETELY INDEPENDENT NOTEBOOK** - Run this after notebook 01.

## What this notebook does:
- ✅ Loads data from `quickstart_catalog_vkm_external.classify_tickets.raw_tickets`  
- ✅ Uses **Databricks AI Functions** for intelligent extraction
- ✅ Extracts actions, priorities, and timelines using LLMs
- ✅ Categorizes action items by type  
- ✅ Saves results to Unity Catalog tables  
- ✅ Ready for next notebook: `03_ai_classification.ipynb`

**Prerequisites:** Run `01_sample_data_generation.ipynb` first

## AI Functions Used:
- `ai_classify` - For priority and category classification
- `ai_extract` - For action items extraction  
- `ai_gen` - For complex analysis and summaries

In [1]:
# Import required libraries
import pandas as pd
import re
from pyspark.sql.functions import *
from pyspark.sql.types import *
import json

# Import configuration
%run ./config

# Define a UDF to extract JSON from AI responses
def extract_json_from_ai_response(text):
    """Extract JSON array from AI response text, handling various formats"""
    if not text:
        return "[]"
    
    # Try to find JSON array pattern
    # Look for [ followed by content and ending with ]
    pattern = r'\[(.*?)\]'
    matches = re.findall(pattern, text, re.DOTALL)
    
    if matches:
        # Take the first match and reconstruct the JSON array
        content = matches[0].strip()
        # Clean up the content - remove extra whitespace and newlines
        content = re.sub(r'\s+', ' ', content)
        return f"[{content}]"
    
    # If no array found, try to extract quoted strings
    quoted_items = re.findall(r'"([^"]+)"', text)
    if quoted_items:
        json_items = [f'"{item}"' for item in quoted_items]
        return f"[{', '.join(json_items)}]"
    
    return "[]"

# Register the UDF
extract_json_udf = udf(extract_json_from_ai_response, StringType())

print("✅ Libraries imported, configuration loaded, and JSON extraction UDF defined")

✅ Libraries imported, configuration loaded, and JSON extraction UDF defined

In [2]:
# Load Sample Data
print("📊 Loading sample ticket data from Unity Catalog...")

# Load the sample ticket data from Unity Catalog
df_tickets = spark.table(TABLES["raw_tickets"])
print(f"✅ Loaded {df_tickets.count()} tickets from: {TABLES['raw_tickets']}")

# Display sample data
print("\n📋 Sample data:")
display(df_tickets.select("ticket_id", "short_description", "description"))

📊 Loading sample ticket data from Unity Catalog...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Loaded 10 tickets from: quickstart_catalog_vkm_external.classify_tickets.raw_tickets

📋 Sample data:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, description: string]

In [3]:
# AI-Powered Extraction Using Databricks AI Functions
print("🤖 Step 1: Classifying ticket priorities using ai_classify...")

# 1. PRIORITY CLASSIFICATION using ai_classify (SQL syntax)
try:
    # Register DataFrame as temporary view for SQL access
    df_tickets.createOrReplaceTempView("tickets")
    
    # Use SQL to call ai_classify
    df_with_priority = spark.sql("""
        SELECT
            *,
            ai_classify(description, ARRAY('Low Priority', 'Medium Priority', 'High Priority', 'Urgent Priority')) as priority_classified
        FROM tickets
    """)
    print("✅ Priority classification completed")
except Exception as e:
    print(f"❌ Error in priority classification: {e}")
    print("🔧 Using rule-based fallback approach...")
    
    # Rule-based priority classification
    df_with_priority = df_tickets.withColumn(
        "priority_classified",
        when(col("description").rlike("(?i)(urgent|critical|emergency|asap|immediately|now)"), lit("Urgent Priority"))
        .when(col("description").rlike("(?i)(high|important|priority|soon|today)"), lit("High Priority"))
        .when(col("description").rlike("(?i)(low|minor|sometime|later|when possible)"), lit("Low Priority"))
        .otherwise(lit("Medium Priority"))
    )
    print("✅ Rule-based priority classification completed")

display(df_with_priority.select("ticket_id", "short_description", "priority_classified"))

🤖 Step 1: Classifying ticket priorities using ai_classify...
✅ Priority classification completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, priority_classified: string]

In [ ]:
# 2. ACTION ITEMS EXTRACTION using ai_gen (better for arrays)
print("🔍 Step 2: Extracting action items using ai_gen...")

# Check if AI functions are available by testing with a simple query
ai_functions_available = False
try:
    # Test AI function availability with a very simple query
    test_df = spark.sql("SELECT ai_gen('test') as test_output")
    test_df.collect()  # Force execution
    ai_functions_available = True
    print("✅ AI functions are available")
except Exception as e:
    print(f"❌ AI functions not available: {e}")
    print("🔧 Using fallback approach without AI functions...")
    ai_functions_available = False

if ai_functions_available:
    try:
        # Register DataFrame as temporary view for SQL access
        df_with_priority.createOrReplaceTempView("tickets_with_priority")
        
        # Use SQL to call ai_gen
        df_with_actions = spark.sql("""
            SELECT
                *,
                ai_gen(
                    CONCAT(
                        'Extract all specific action items, tasks, requirements, and deliverables from this ticket description. Return as a JSON array of strings. Each item should be a concrete, actionable task. If no action items are found, return an empty array []. Ticket description: ',
                        description
                    )
                ) AS action_items_raw
            FROM tickets_with_priority
        """)
        print("✅ AI-powered action extraction completed")
        
    except Exception as e:
        print(f"❌ Error in AI extraction: {e}")
        print("🔧 Falling back to non-AI approach...")
        ai_functions_available = False

if not ai_functions_available:
    # Fallback: Create a simple extraction without AI
    print("🔧 Using rule-based extraction as fallback...")
    
    # Simple rule-based extraction - look for common action words
    df_with_actions = df_with_priority.withColumn(
        "action_items_raw",
        when(
            col("description").rlike("(?i)(install|setup|configure|deploy|update|fix|resolve|implement|create|build|test|monitor|backup|restore|migrate|upgrade|patch|secure|optimize|troubleshoot|investigate|analyze|review|document|train|schedule|plan|design|develop|maintain|manage|administer|operate|support|service)"),
            lit('["Action item extracted from description"]')
        ).otherwise(lit("[]"))
    )
    print("✅ Rule-based action extraction completed")

# Debug: Let's see what the raw output looks like
print("🔍 Debug: Raw AI output for first ticket:")
df_with_actions.select("ticket_id", "action_items_raw").show(1, truncate=False)

# Clean the raw AI output to extract pure JSON using UDF
# The AI often returns JSON wrapped in markdown code blocks, so we need to extract just the JSON part
df_with_actions_cleaned = df_with_actions.withColumn(
    "action_items_cleaned",
    extract_json_udf(col("action_items_raw"))
)

# Debug: Let's see what the cleaned output looks like
print("🔍 Debug: Cleaned JSON for first ticket:")
df_with_actions_cleaned.select("ticket_id", "action_items_cleaned").show(1, truncate=False)

# Additional debug: Let's see the full raw output for debugging
print("🔍 Debug: Full raw output for first ticket:")
df_with_actions.select("ticket_id", "action_items_raw").show(1, truncate=False)

# Parse the cleaned JSON response and convert to array
try:
    df_with_actions_parsed = df_with_actions_cleaned.withColumn(
        "action_items_extracted",
        from_json(col("action_items_cleaned"), ArrayType(StringType()))
    ).withColumn(
        "action_items_extracted",
        when(col("action_items_extracted").isNull(), array()).otherwise(col("action_items_extracted"))
    ).drop("action_items_raw", "action_items_cleaned")
    print("✅ JSON parsing completed successfully")
except Exception as e:
    print(f"❌ Error in JSON parsing: {e}")
    print("🔧 Using fallback parsing approach...")
    
    # Fallback: Create action_items_extracted directly from the raw data
    df_with_actions_parsed = df_with_actions_cleaned.withColumn(
        "action_items_extracted",
        when(col("action_items_cleaned") == "[]", array())
        .when(col("action_items_cleaned").rlike(r'^\[.*\]$'), 
              split(regexp_replace(col("action_items_cleaned"), r'[\[\]"]', ''), ','))
        .otherwise(array(col("action_items_cleaned")))
    ).drop("action_items_raw", "action_items_cleaned")
    print("✅ Fallback parsing completed")

print("✅ Action items extraction completed")

# Debug: Let's see the final parsed action items
print("🔍 Debug: Final parsed action items for first ticket:")
try:
    df_with_actions_parsed.select("ticket_id", "action_items_extracted").show(1, truncate=False)
    
    # Additional debugging - check the schema and data types
    print("🔍 Debug: Schema of action_items_extracted column:")
    df_with_actions_parsed.select("action_items_extracted").dtypes
    
    print("🔍 Debug: Sample of raw action_items_raw:")
    df_with_actions_parsed.select("ticket_id", "action_items_raw").show(2, truncate=False)
    
except Exception as e:
    print(f"❌ Error in debug section: {e}")
    print("🔍 Debug: Available columns:")
    print(df_with_actions_parsed.columns)

# Additional debug: Check if any tickets have non-empty action items
print("🔍 Debug: Count of tickets with non-empty action items:")
try:
    # Check if action_items_extracted column exists and is an array
    if "action_items_extracted" in df_with_actions_parsed.columns:
        # Try to count non-empty arrays
        non_empty_count = df_with_actions_parsed.filter(
            col("action_items_extracted").isNotNull() & 
            (size(col("action_items_extracted")) > 0)
        ).count()
        print(f"   Non-empty action items: {non_empty_count}")
        
        # Show sample of tickets with action items
        print("🔍 Debug: Sample of tickets with action items:")
        df_with_actions_parsed.filter(
            col("action_items_extracted").isNotNull() & 
            (size(col("action_items_extracted")) > 0)
        ).select("ticket_id", "action_items_extracted").show(5, truncate=False)
    else:
        print("   action_items_extracted column not found")
except Exception as e:
    print(f"   Error checking action items: {e}")
    print("   Showing first few rows of action_items_extracted column:")
    df_with_actions_parsed.select("ticket_id", "action_items_extracted").show(5, truncate=False)

display(df_with_actions_parsed.select("ticket_id", "short_description", "action_items_extracted"))

🔍 Step 2: Extracting action items using ai_gen...
✅ AI functions are available
🔍 Debug: Raw AI output for first ticket:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|Here are the extracted action items as a JSON array of strings:\n\n```\n[\n  "Investigate the cause of the website's slow performance",\n  "Check the database for potential issues",\n  "Look into the website's performance since this morning"\n]\n```\n\nNote that the original text is somewhat vague, so I've tried to break down the request into concrete, actionable tasks. However, it's worth noting that the tasks are still somewhat high-level and may require further clarification or breakdown into more specific, technical tasks. \n\nAlternatively, a more detailed and technical set of action items could be:\n\n```\n[\n  "Check database query logs for slow queries",\n  "Monitor database connection pool usage",\n  "Verify database indexing and optimization",\n  "Check website server logs for errors",\n  "Run a website performance benchmarking test",\n  "Investigate recent changes to the website or database that may be causing the issue"\n]\n```\n\nBut these are more speculative and may not be directly implied by the original text.|
+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 1 row
🔍 Debug: Cleaned JSON for first ticket:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_cleaned                                                                                                                                            |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|["Investigate the cause of the website's slow performance", "Check the database for potential issues", "Look into the website's performance since this morning"]|
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 1 row
🔍 Debug: Full raw output for first ticket:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|Here are the extracted action items as a JSON array of strings:\n\n```\n[\n  "Investigate the cause of the website's slow performance",\n  "Check the database for potential issues",\n  "Look into the website's performance since this morning"\n]\n```\n\nNote that the original text is somewhat vague, so I've tried to interpret the requests into concrete action items. A more explicit request might have yielded more specific tasks, but these should cover the general requirements mentioned in the ticket description.|
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 1 row
✅ Action items extraction completed
🔍 Debug: Final parsed action items for first ticket:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_extracted                                                                                                                                    |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|[Investigate the cause of the website's slow performance, Check the database for potential issues, Look into the website's performance since this morning]|
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 1 row
🔍 Debug: Count of tickets with non-empty action items:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

🔍 Debug: Sample of tickets with action items:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_extracted                                                                                                                                    |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|[Investigate the cause of the website's slow performance, Check the database for potential issues, Look into the website's performance since this morning]|
|TICKET_002|[Fix the login system, Investigate the cause of the login system failure, Prevent the login system from breaking again]                                   |
|TICKET_003|[Debug the API to identify the cause of the random errors]                                                                                                |
|TICKET_004|[Investigate monitoring alerts, Determine cause of false positives or actual issues, Verify app functionality]                                            |
|TICKET_005|[Figure out what went wrong with the deployment, Improve testing to prevent similar failures in the future]                                               |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 5 rows

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_items_extracted: array<string>]

In [5]:
# 3. MAIN ACTION REQUEST using ai_gen (SQL syntax)
print("🎯 Step 3: Extracting main action request using ai_gen...")

if ai_functions_available:
    try:
        # Register DataFrame as temporary view for SQL access
        df_with_actions_parsed.createOrReplaceTempView("tickets_with_actions_parsed")
        
        # Use SQL to call ai_gen
        df_with_main_action = spark.sql("""
            SELECT
                *,
                ai_gen(
                    CONCAT(
                        'Extract the main action or request from this ticket description. Return only the specific action requested, not a list of items. If no clear action is requested, return None. Ticket description: ',
                        description
                    )
                ) AS action_requested
            FROM tickets_with_actions_parsed
        """)
        print("✅ Main action request extraction completed")
    except Exception as e:
        print(f"❌ Error in main action extraction: {e}")
        print("🔧 Using fallback approach...")
        ai_functions_available = False

if not ai_functions_available:
    # Rule-based main action extraction
    df_with_main_action = df_with_actions_parsed.withColumn(
        "action_requested",
        when(col("description").rlike("(?i)(install|setup|configure|deploy|update|fix|resolve|implement|create|build|test|monitor|backup|restore|migrate|upgrade|patch|secure|optimize|troubleshoot|investigate|analyze|review|document|train|schedule|plan|design|develop|maintain|manage|administer|operate|support|service)"),
             regexp_extract(col("description"), "(?i)(install|setup|configure|deploy|update|fix|resolve|implement|create|build|test|monitor|backup|restore|migrate|upgrade|patch|secure|optimize|troubleshoot|investigate|analyze|review|document|train|schedule|plan|design|develop|maintain|manage|administer|operate|support|service)", 1))
        .otherwise(lit("General request"))
    )
    print("✅ Rule-based main action extraction completed")

display(df_with_main_action.select("ticket_id", "short_description", "action_requested"))

# 4. TIMELINE EXTRACTION using ai_gen (SQL syntax)
print("⏰ Step 4: Extracting timeline information using ai_gen...")

if ai_functions_available:
    try:
        # Register DataFrame as temporary view for SQL access
        df_with_main_action.createOrReplaceTempView("tickets_with_main_action")
        
        # Use SQL to call ai_gen
        df_with_timeline = spark.sql("""
            SELECT
                *,
                ai_gen(
                    CONCAT(
                        'Extract timeline information from this ticket description. Look for due dates, deadlines, urgency indicators, or time references. Return the specific timeline mentioned, or None if no timeline is specified. Ticket description: ',
                        description
                    )
                ) AS timeline_extracted
            FROM tickets_with_main_action
        """)
        print("✅ Timeline extraction completed")
    except Exception as e:
        print(f"❌ Error in timeline extraction: {e}")
        print("🔧 Using fallback approach...")
        ai_functions_available = False

if not ai_functions_available:
    # Rule-based timeline extraction
    df_with_timeline = df_with_main_action.withColumn(
        "timeline_extracted",
        when(col("description").rlike("(?i)(urgent|asap|immediately|today|tomorrow|this week|next week|this month|deadline|due)"),
             regexp_extract(col("description"), "(?i)(urgent|asap|immediately|today|tomorrow|this week|next week|this month|deadline|due)", 1))
        .otherwise(lit("No specific timeline"))
    )
    print("✅ Rule-based timeline extraction completed")
display(df_with_timeline.select("ticket_id", "short_description", "timeline_extracted"))

🎯 Step 3: Extracting main action request using ai_gen...
✅ Main action request extraction completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_requested: string]

⏰ Step 4: Extracting timeline information using ai_gen...
✅ Timeline extraction completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, timeline_extracted: string]

In [6]:
# Action Items Categorization
print("🏷️ Step 5: Categorizing action items...")

# Explode action items to create one row per action item
df_action_items_exploded = df_with_timeline.select(
    "ticket_id",
    "short_description", 
    "action_requested",
    "priority_classified",
    "timeline_extracted",
    explode("action_items_extracted").alias("action_item")
).filter(col("action_item").isNotNull())

print(f"✅ Exploded {df_action_items_exploded.count()} individual action items")

# Categorize action items using ai_classify (SQL syntax)
if ai_functions_available:
    try:
        # Register DataFrame as temporary view for SQL access
        df_action_items_exploded.createOrReplaceTempView("action_items_exploded")
        
        # Use SQL to call ai_classify
        df_action_items_categorized = spark.sql("""
            SELECT
                *,
                ai_classify(action_item, ARRAY('Infrastructure', 'Security', 'Monitoring', 'Testing', 'Documentation', 'Network', 'Database', 'Application', 'Other')) as action_category
            FROM action_items_exploded
        """)
        print("✅ Action items categorization completed")
    except Exception as e:
        print(f"❌ Error in action categorization: {e}")
        print("🔧 Using fallback approach...")
        ai_functions_available = False

if not ai_functions_available:
    # Rule-based action categorization
    df_action_items_categorized = df_action_items_exploded.withColumn(
        "action_category",
        when(col("action_item").rlike("(?i)(server|infrastructure|cloud|vm|container|kubernetes|docker)"), lit("Infrastructure"))
        .when(col("action_item").rlike("(?i)(security|auth|permission|access|encrypt|firewall|vulnerability)"), lit("Security"))
        .when(col("action_item").rlike("(?i)(monitor|alert|log|metric|dashboard|health)"), lit("Monitoring"))
        .when(col("action_item").rlike("(?i)(test|testing|qa|validation|verify)"), lit("Testing"))
        .when(col("action_item").rlike("(?i)(document|doc|readme|guide|manual)"), lit("Documentation"))
        .when(col("action_item").rlike("(?i)(network|dns|load|balancer|proxy|vpn)"), lit("Network"))
        .when(col("action_item").rlike("(?i)(database|db|sql|data|table|query)"), lit("Database"))
        .when(col("action_item").rlike("(?i)(app|application|api|service|microservice)"), lit("Application"))
        .otherwise(lit("Other"))
    )
    print("✅ Rule-based action categorization completed")

display(df_action_items_categorized)

🏷️ Step 5: Categorizing action items...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Exploded 26 individual action items
✅ Action items categorization completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_requested: string, priority_classified: string, timeline_extracted: string, action_item: string, action_category: string]

In [7]:
# Save Extracted Data
print("💾 Step 6: Saving extracted data to Unity Catalog...")

try:
    # Cache the DataFrames to avoid recomputation
    df_with_timeline.cache()
    df_action_items_categorized.cache()
    
    # Save the main extracted data to Unity Catalog
    df_with_timeline.write.format("delta").mode("overwrite").saveAsTable(TABLES["tickets_with_actions"])
    print("✅ Main data saved successfully!")
    
    # Save the categorized action items to Unity Catalog  
    df_action_items_categorized.write.format("delta").mode("overwrite").saveAsTable(TABLES["action_items_detailed"])
    print("✅ Action items saved successfully!")
    
    print("✅ AI-extracted data saved to Unity Catalog Delta tables:")
    print(f"📊 Main data: {TABLES['tickets_with_actions']}")
    print(f"📋 Action items: {TABLES['action_items_detailed']}")
    
    # Show summary statistics (with error handling)
    print(f"\n📈 Summary Statistics:")
    try:
        ticket_count = df_with_timeline.count()
        print(f"   Total tickets processed: {ticket_count}")
    except Exception as e:
        print(f"   Error counting tickets: {e}")
    
    try:
        action_count = df_action_items_categorized.count()
        print(f"   Total action items extracted: {action_count}")
    except Exception as e:
        print(f"   Error counting action items: {e}")
    
    # Show action category distribution (with error handling)
    print(f"\n📊 Action Category Distribution:")
    try:
        df_action_items_categorized.groupBy("action_category").count().orderBy(desc("count")).show()
    except Exception as e:
        print(f"   Error showing action categories: {e}")
    
    # Show priority distribution (with error handling)
    print(f"\n🎯 Priority Distribution:")
    try:
        df_with_timeline.groupBy("priority_classified").count().orderBy(desc("count")).show()
    except Exception as e:
        print(f"   Error showing priority distribution: {e}")
    
    print("\n🎯 Ready for next notebook: 03_ai_classification.ipynb")
    
except Exception as e:
    print(f"❌ Error saving data: {e}")
    print("🔍 Trying to save to temporary tables...")
    try:
        df_with_timeline.write.format("delta").mode("overwrite").saveAsTable("tickets_with_actions_temp")
        df_action_items_categorized.write.format("delta").mode("overwrite").saveAsTable("action_items_detailed_temp")
        print("✅ Saved to temporary tables")
    except Exception as e2:
        print(f"❌ Error with temp tables: {e2}")

# Alternative: Simple completion message without expensive operations
print("\n" + "="*50)
print("🎉 NOTEBOOK COMPLETED SUCCESSFULLY!")
print("="*50)
print("✅ Data has been saved to Unity Catalog")
print("✅ Action items have been extracted and categorized")
print("✅ Ready to proceed to next notebook: 03_ai_classification.ipynb")
print("="*50)

💾 Step 6: Saving extracted data to Unity Catalog...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Main data saved successfully!

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Action items saved successfully!
✅ AI-extracted data saved to Unity Catalog Delta tables:
📊 Main data: quickstart_catalog_vkm_external.classify_tickets.tickets_with_actions
📋 Action items: quickstart_catalog_vkm_external.classify_tickets.action_items_detailed

📈 Summary Statistics:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

   Total tickets processed: 10

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

   Total action items extracted: 26

📊 Action Category Distribution:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+---------------+-----+
|action_category|count|
+---------------+-----+
|     Monitoring|    7|
|    Application|    6|
|        Testing|    4|
|       Security|    3|
| Infrastructure|    3|
|       Database|    3|
+---------------+-----+


🎯 Priority Distribution:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-------------------+-----+
|priority_classified|count|
+-------------------+-----+
|    Urgent Priority|    6|
|      High Priority|    3|
|    Medium Priority|    1|
+-------------------+-----+


🎯 Ready for next notebook: 03_ai_classification.ipynb

==================================================
🎉 NOTEBOOK COMPLETED SUCCESSFULLY!
==================================================
✅ Data has been saved to Unity Catalog
✅ Action items have been extracted and categorized
✅ Ready to proceed to next notebook: 03_ai_classification.ipynb
==================================================