# 🔍 02 - AI-Powered Action Extraction

**COMPLETELY INDEPENDENT NOTEBOOK** - Run this after notebook 01.

## What this notebook does:
- ✅ Loads data from `quickstart_catalog_vkm_external.classify_tickets.raw_tickets`  
- ✅ Uses **Databricks AI Functions** for intelligent extraction
- ✅ Extracts actions, priorities, and timelines using LLMs
- ✅ Categorizes action items by type  
- ✅ Saves results to Unity Catalog tables  
- ✅ Ready for next notebook: `03_ai_classification.ipynb`

**Prerequisites:** Run `01_sample_data_generation.ipynb` first

## AI Functions Used:
- `ai_classify` - For priority and category classification
- `ai_extract` - For action items extraction  
- `ai_gen` - For complex analysis and summaries

In [1]:
# Import required libraries
import pandas as pd
import re
from pyspark.sql.functions import *
from pyspark.sql.types import *
import json

# Import configuration
%run ./config

print("✅ Libraries imported and configuration loaded")

✅ Libraries imported and configuration loaded

In [2]:
# Load Sample Data
print("📊 Loading sample ticket data from Unity Catalog...")

# Load the sample ticket data from Unity Catalog
df_tickets = spark.table(TABLES["raw_tickets"])
print(f"✅ Loaded {df_tickets.count()} tickets from: {TABLES['raw_tickets']}")

# Display sample data
print("\n📋 Sample data:")
display(df_tickets.select("ticket_id", "short_description", "description"))

📊 Loading sample ticket data from Unity Catalog...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Loaded 10 tickets from: quickstart_catalog_vkm_external.classify_tickets.raw_tickets

📋 Sample data:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, description: string]

In [3]:
# AI-Powered Extraction Using Databricks AI Functions
print("🤖 Step 1: Classifying ticket priorities using ai_classify...")

# 1. PRIORITY CLASSIFICATION using ai_classify (SQL syntax)
df_with_priority = df_tickets.selectExpr(
    "*",
    "ai_classify(description, ARRAY('Low Priority', 'Medium Priority', 'High Priority', 'Urgent Priority')) as priority_classified"
)

print("✅ Priority classification completed")
display(df_with_priority.select("ticket_id", "short_description", "priority_classified"))

🤖 Step 1: Classifying ticket priorities using ai_classify...
✅ Priority classification completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, priority_classified: string]

In [4]:
# 2. ACTION ITEMS EXTRACTION using ai_gen (better for arrays)
print("🔍 Step 2: Extracting action items using ai_gen...")

df_with_actions = df_with_priority.selectExpr(
    "*",
    "ai_gen(CONCAT('Extract all specific action items, tasks, requirements, and deliverables from this ticket description. Return as a JSON array of strings. Each item should be a concrete, actionable task. If no action items are found, return an empty array []. Ticket description: ', description)) as action_items_raw"
)

# Debug: Let's see what the raw output looks like
print("🔍 Debug: Raw AI output for first ticket:")
df_with_actions.select("ticket_id", "action_items_raw").show(1, truncate=False)

# Parse the JSON response and convert to array
df_with_actions_parsed = df_with_actions.withColumn(
    "action_items_extracted",
    from_json(col("action_items_raw"), ArrayType(StringType()))
).withColumn(
    "action_items_extracted",
    when(col("action_items_extracted").isNull(), array()).otherwise(col("action_items_extracted"))
).drop("action_items_raw")

print("✅ Action items extraction completed")
display(df_with_actions_parsed.select("ticket_id", "short_description", "action_items_extracted"))

🔍 Step 2: Extracting action items using ai_gen...
🔍 Debug: Raw AI output for first ticket:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|ticket_id |action_items_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|TICKET_001|Here are the extracted action items as a JSON array of strings:\n\n```\n[\n  "Investigate the cause of the website's slow performance",\n  "Check the database for potential issues",\n  "Look into the website's performance since this morning"\n]\n```\n\nNote that the original text is somewhat vague, so I've tried to break down the request into concrete, actionable tasks. However, it's worth noting that the tasks are still somewhat high-level and may require further clarification or breakdown into more specific, technical tasks. \n\nAlternatively, a more detailed and technical set of action items could be:\n\n```\n[\n  "Check database query logs for slow queries",\n  "Monitor database connection pool usage",\n  "Verify database indexing and optimization",\n  "Check server resource utilization (CPU, memory, disk)",\n  "Investigate recent code changes or deployments",\n  "Run a website performance profiling tool"\n]\n```\n\nBut these are just examples, and the original text does not explicitly mention these specific tasks.|
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 1 row
✅ Action items extraction completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_items_extracted: array<string>]

In [5]:
# 3. MAIN ACTION REQUEST using ai_gen (SQL syntax)
print("🎯 Step 3: Extracting main action request using ai_gen...")

df_with_main_action = df_with_actions_parsed.selectExpr(
    "*",
    "ai_gen(CONCAT('Extract the main action or request from this ticket description. Return only the specific action requested, not a list of items. If no clear action is requested, return None. Ticket description: ', description)) as action_requested"
)

print("✅ Main action request extraction completed")
display(df_with_main_action.select("ticket_id", "short_description", "action_requested"))

# 4. TIMELINE EXTRACTION using ai_gen (SQL syntax)
print("⏰ Step 4: Extracting timeline information using ai_gen...")

df_with_timeline = df_with_main_action.selectExpr(
    "*",
    "ai_gen(CONCAT('Extract timeline information from this ticket description. Look for due dates, deadlines, urgency indicators, or time references. Return the specific timeline mentioned, or None if no timeline is specified. Ticket description: ', description)) as timeline_extracted"
)

print("✅ Timeline extraction completed")
display(df_with_timeline.select("ticket_id", "short_description", "timeline_extracted"))

🎯 Step 3: Extracting main action request using ai_gen...
✅ Main action request extraction completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_requested: string]

⏰ Step 4: Extracting timeline information using ai_gen...
✅ Timeline extraction completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, timeline_extracted: string]

In [6]:
# Action Items Categorization
print("🏷️ Step 5: Categorizing action items...")

# Explode action items to create one row per action item
df_action_items_exploded = df_with_timeline.select(
    "ticket_id",
    "short_description", 
    "action_requested",
    "priority_classified",
    "timeline_extracted",
    explode("action_items_extracted").alias("action_item")
).filter(col("action_item").isNotNull())

print(f"✅ Exploded {df_action_items_exploded.count()} individual action items")

# Categorize action items using ai_classify (SQL syntax)
df_action_items_categorized = df_action_items_exploded.selectExpr(
    "*",
    "ai_classify(action_item, ARRAY('Infrastructure', 'Security', 'Monitoring', 'Testing', 'Documentation', 'Network', 'Database', 'Application', 'Other')) as action_category"
)

print("✅ Action items categorization completed")
display(df_action_items_categorized)

🏷️ Step 5: Categorizing action items...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Exploded 0 individual action items
✅ Action items categorization completed

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ticket_id: string, short_description: string, action_requested: string, priority_classified: string, timeline_extracted: string, action_item: string, action_category: string]

In [7]:
# Save Extracted Data
print("💾 Step 6: Saving extracted data to Unity Catalog...")

try:
    # Save the main extracted data to Unity Catalog
    df_with_timeline.write.format("delta").mode("overwrite").saveAsTable(TABLES["tickets_with_actions"])
    print("✅ Main data saved successfully!")
    
    # Save the categorized action items to Unity Catalog  
    df_action_items_categorized.write.format("delta").mode("overwrite").saveAsTable(TABLES["action_items_detailed"])
    print("✅ Action items saved successfully!")
    
    print("✅ AI-extracted data saved to Unity Catalog Delta tables:")
    print(f"📊 Main data: {TABLES['tickets_with_actions']}")
    print(f"📋 Action items: {TABLES['action_items_detailed']}")
    
    # Show summary statistics
    print(f"\n📈 Summary Statistics:")
    print(f"   Total tickets processed: {df_with_timeline.count()}")
    print(f"   Total action items extracted: {df_action_items_categorized.count()}")
    
    # Show action category distribution
    print(f"\n📊 Action Category Distribution:")
    df_action_items_categorized.groupBy("action_category").count().orderBy(desc("count")).show()
    
    # Show priority distribution
    print(f"\n🎯 Priority Distribution:")
    df_with_timeline.groupBy("priority_classified").count().orderBy(desc("count")).show()
    
    print("\n🎯 Ready for next notebook: 03_ai_classification.ipynb")
    
except Exception as e:
    print(f"❌ Error saving data: {e}")
    print("🔍 Trying to save to temporary tables...")
    try:
        df_with_timeline.write.format("delta").mode("overwrite").saveAsTable("tickets_with_actions_temp")
        df_action_items_categorized.write.format("delta").mode("overwrite").saveAsTable("action_items_detailed_temp")
        print("✅ Saved to temporary tables")
    except Exception as e2:
        print(f"❌ Error with temp tables: {e2}")

💾 Step 6: Saving extracted data to Unity Catalog...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Main data saved successfully!

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

✅ Action items saved successfully!
✅ AI-extracted data saved to Unity Catalog Delta tables:
📊 Main data: quickstart_catalog_vkm_external.classify_tickets.tickets_with_actions
📋 Action items: quickstart_catalog_vkm_external.classify_tickets.action_items_detailed

📈 Summary Statistics:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

   Total tickets processed: 10

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

   Total action items extracted: 0

📊 Action Category Distribution:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+---------------+-----+
|action_category|count|
+---------------+-----+
+---------------+-----+


🎯 Priority Distribution:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-------------------+-----+
|priority_classified|count|
+-------------------+-----+
|    Urgent Priority|    6|
|      High Priority|    3|
|    Medium Priority|    1|
+-------------------+-----+


🎯 Ready for next notebook: 03_ai_classification.ipynb