# 🔮 04 - AI Forecasting with Databricks ai_forecast

**Predictive Analytics for Ticket Management** - 

## What this notebook does:
- ✅ Prepares time series data from ticket analysis results
- ✅ Uses Databricks `ai_forecast` function for predictive analytics
- ✅ Forecasts ticket volume, priority trends, and system health patterns
- ✅ Creates asset failure prediction models
- ✅ Generates actionable insights for proactive maintenance

**Prerequisites:** Run notebooks 01, 02, and 03 first

## Key Forecasting Use Cases:
- 📈 **Ticket Volume Prediction**: Forecast future ticket volumes by category
- ⚠️ **Critical Issue Forecasting**: Predict when critical issues might spike
- 🔧 **Asset Failure Prediction**: Identify systems likely to fail based on ticket patterns
- 📊 **Resource Planning**: Forecast team workload and resource needs
- 🎯 **Proactive Maintenance**: Schedule maintenance before failures occur

## Databricks ai_forecast Function:
Based on [Microsoft's ai_forecast documentation](https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual/functions/ai_forecast), this function provides:
- Prophet-like piecewise linear and seasonality modeling
- Automatic frequency detection
- Prediction intervals with confidence levels
- Multi-metric and multi-group forecasting
- Built-in seasonality handling

## ⚠️ Important: This notebook requires a Serverless SQL warehouse
All code is pure SQL - no Python cells or print statements.

In [ ]:
-- Step 1: Check available data and table structure
-- This query verifies the ai_showcase_results table exists and shows sample data

SELECT 
    ticket_id,
    ai_priority_classification,
    urgency_level,
    affected_systems,
    ai_showcase_timestamp
FROM quickstart_catalog_vkm_external.classify_tickets.ai_showcase_results
LIMIT 3;

✅ Libraries imported and configuration loaded
🎯 Using Unity Catalog: quickstart_catalog_vkm_external.classify_tickets
🔮 Ready for AI forecasting with Databricks ai_forecast function (SQL mode)
⚠️  Note: ai_forecast requires Serverless SQL warehouse - all code uses SQL

In [ ]:
-- Step 2: Create daily aggregated data for forecasting
-- This creates a temporary view with daily ticket counts by priority and system

CREATE OR REPLACE TEMPORARY VIEW daily_tickets AS
SELECT 
    DATE(ai_showcase_timestamp) as date,
    ai_priority_classification,
    affected_systems,
    COUNT(ticket_id) as ticket_count,
    COUNT(CASE WHEN urgency_level = 'High' THEN 1 END) as high_urgency_count,
    COUNT(CASE WHEN urgency_level = 'Critical' THEN 1 END) as critical_urgency_count
FROM quickstart_catalog_vkm_external.classify_tickets.ai_showcase_results
GROUP BY 
    DATE(ai_showcase_timestamp),
    ai_priority_classification,
    affected_systems
ORDER BY date;

-- Display sample aggregated data
SELECT * FROM daily_tickets LIMIT 10;

IndentationError: unexpected indent (1768999265.py, line 12)

In [ ]:
-- Step 3: Create overall ticket volume time series
-- This aggregates daily data for overall volume forecasting

CREATE OR REPLACE TEMPORARY VIEW ticket_volume_ts AS
SELECT 
    date,
    SUM(ticket_count) as total_tickets,
    SUM(high_urgency_count) as high_urgency_tickets,
    SUM(critical_urgency_count) as critical_urgency_tickets
FROM daily_tickets
GROUP BY date
ORDER BY date;

-- Display the time series data
SELECT * FROM ticket_volume_ts;

⏰ Step 2: Preparing time series data...
✅ Daily aggregated data prepared

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

📅 Date range: Row(min(date)='2025-09-20', max(date)='2025-09-20')

📊 Sample daily aggregated data:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[date: string, ai_priority_classification: string, affected_systems: string, ticket_count: bigint, high_urgency_count: bigint, critical_urgency_count: bigint]

In [ ]:
-- Step 4: Forecast future ticket volumes using ai_forecast
-- This uses the AI_FORECAST function to predict 30 days ahead

-- First, check the date range
SELECT 
    MIN(date) as min_date,
    MAX(date) as max_date,
    COUNT(*) as total_days
FROM ticket_volume_ts;

-- Run AI forecast for ticket volumes (30-day horizon)
SELECT * FROM AI_FORECAST(
    TABLE(ticket_volume_ts),
    horizon => DATE_ADD((SELECT MAX(date) FROM ticket_volume_ts), 30),
    time_col => 'date',
    value_col => ARRAY('total_tickets', 'high_urgency_tickets', 'critical_urgency_tickets'),
    prediction_interval_width => 0.95,
    frequency => '1D',
    parameters => '{"global_floor": 0}'
)
ORDER BY date;

📈 Step 3: Creating overall ticket volume time series...
✅ Overall ticket volume time series created

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

📊 Total data points: 1

📈 Ticket volume time series:

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[date: string, total_tickets: bigint, high_urgency_tickets: bigint, critical_urgency_tickets: bigint]

In [ ]:
-- Step 5: Create system health indicators for asset failure prediction
-- This calculates health scores based on ticket patterns

CREATE OR REPLACE TEMPORARY VIEW system_health_ts AS
SELECT 
    date,
    affected_systems,
    SUM(ticket_count) as total_issues,
    SUM(critical_urgency_count) as critical_issues,
    CASE 
        WHEN SUM(ticket_count) > 0 
        THEN SUM(critical_urgency_count) / SUM(ticket_count) 
        ELSE 0 
    END as critical_ratio,
    -- Calculate system health score (lower is better)
    (SUM(ticket_count) * 0.3 + SUM(critical_urgency_count) * 0.7 + 
     CASE WHEN SUM(ticket_count) > 0 THEN (SUM(critical_urgency_count) / SUM(ticket_count)) * 10 ELSE 0 END) as health_score
FROM daily_tickets
WHERE affected_systems IS NOT NULL AND affected_systems != 'Unknown'
GROUP BY date, affected_systems
ORDER BY affected_systems, date;

-- Display system health data
SELECT * FROM system_health_ts LIMIT 10;

🔮 Step 4: Forecasting future ticket volumes using ai_forecast...

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

📅 Forecasting from 2025-09-20 to 2025-10-20

{"ts": "2025-09-20 16:30:22.484", "level": "ERROR", "logger": "SQLQueryContextLogger", "msg": "[UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW] The feature is not supported: AI function ai_forecast is in preview and currently disabled in this environment. SQLSTATE: 0A000; line 2 pos 14\n\nJVM stacktrace:\norg.apache.spark.sql.AnalysisException\n\tat org.apache.spark.sql.errors.QueryCompilationErrors$.aiFunctionPreviewUnavailable(QueryCompilationErrors.scala:5310)\n\tat org.apache.spark.sql.execution.python.UserDefinedPythonTableFunction.builder(UserDefinedPythonFunction.scala:155)\n\tat com.databricks.sql.api.python.BuiltinPythonFunctions$.$anonfun$pythonTableFunction$1(BuiltinPythonFunctions.scala:71)\n\tat org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction(FunctionRegistry.scala:251)\n\tat org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction$(FunctionRegistry.scala:245)\n\tat org.apache.spark.sql.catalyst.analysis.SimpleTableFunctionRegistry.lookupFunction(FunctionRegistry.scala:1317)\n\tat org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.$anonfun$resolveBuiltinOrTempFunctionInternal$1(SessionCatalog.scala:3198)\n\tat org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.lookupTempFuncWithViewContext(SessionCatalog.scala:3209)\n\tat org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempFunctionInternal(SessionCatalog.scala:3198)\n\tat org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempTableFunction(SessionCatalog.scala:3185)\n\tat org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction(DelegatingSessionCatalog.scala:552)\n\tat org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction$(DelegatingSessionCatalog.scala:549)\n\tat com.databricks.sql.managedcatalog.ManagedCatalogSessionCatalog.resolveBuiltinOrTempTableFunction(ManagedCatalogSessionCatalog.scala:89)\n\tat org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveBuiltinOrTempTableFunction(FunctionResolution.scala:147)\n\tat org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveTableValuedFunction(FunctionResolution.scala:156)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.$anonfun$applyOrElse$173(Analyzer.scala:2783)\n\tat org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:107)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2780)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2757)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:141)\n\tat org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:85)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:141)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)\n\tat org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:42)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$2(AnalysisHelper.scala:138)\n\tat org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1330)\n\tat org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1329)\n\tat org.apache.spark.sql.catalyst.plans.logical.Project.mapChildren(basicLogicalOperators.scala:93)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)\n\tat org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:42)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$.apply(Analyzer.scala:2757)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$.apply(Analyzer.scala:2752)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$16(RuleExecutor.scala:480)\n\tat org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule(RuleExecutor.scala:629)\n\tat org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule$(RuleExecutor.scala:613)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.processRule(RuleExecutor.scala:131)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$15(RuleExecutor.scala:480)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$14(RuleExecutor.scala:479)\n\tat scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)\n\tat scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)\n\tat scala.collection.immutable.List.foldLeft(List.scala:79)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$13(RuleExecutor.scala:475)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.executeBatch$1(RuleExecutor.scala:452)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$22(RuleExecutor.scala:585)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$22$adapted(RuleExecutor.scala:585)\n\tat scala.collection.immutable.List.foreach(List.scala:333)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:585)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:349)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeSameContext(Analyzer.scala:507)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:500)\n\tat org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:406)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:500)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:425)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:341)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:233)\n\tat org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:341)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:252)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:96)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:131)\n\tat org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:87)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:487)\n\tat org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:425)\n\tat org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:487)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$3(QueryExecution.scala:308)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:562)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$6(QueryExecution.scala:703)\n\tat org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:152)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:703)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1342)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:696)\n\tat com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:692)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:692)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:295)\n\tat com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:80)\n\tat org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:294)\n\tat scala.util.Try$.apply(Try.scala:210)\n\tat org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)\n\tat org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)\n\tat org.apache.spark.util.LazyTry.get(LazyTry.scala:58)\n\tat org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:340)\n\tat org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:274)\n\tat org.apache.spark.sql.Dataset$.$anonfun$ofRows$3(Dataset.scala:149)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1470)\n\tat com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)\n\tat org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1470)\n\tat org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:141)\n\tat org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:1143)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.SparkSession.sql(SparkSession.scala:1095)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:3606)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:3435)\n\tat org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3370)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:413)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:312)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:233)\n\tat org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:464)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)\n\tat org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:464)\n\tat org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)\n\tat org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:90)\n\tat org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:241)\n\tat org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:89)\n\tat org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:463)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:233)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:614)\n\tat scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)\n\tat com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)\n\tat com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)\n\tat com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)\n\tat scala.util.Using$.resource(Using.scala:261)\n\tat com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)\n\tat org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:614)", "context": {"errorClass": "UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW"}, "exception": {"class": "_MultiThreadedRendezvous", "msg": "<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.INTERNAL\n\tdetails = \"[UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW] The feature is not supported: AI function ai_forecast is in preview and currently disabled in this environment. SQLSTATE: 0A000; line 2 pos 14\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer  {created_time:\"2025-09-20T16:30:22.281607-04:00\", grpc_status:13, grpc_message:\"[UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW] The feature is not supported: AI function ai_forecast is in preview and currently disabled in this environment. SQLSTATE: 0A000; line 2 pos 14\"}\"\n>", "stacktrace": [{"class": null, "method": "_execute_and_fetch_as_iterator", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py", "line": "1932"}, {"class": null, "method": "__next__", "file": "<frozen _collections_abc>", "line": "356"}, {"class": null, "method": "send", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "141"}, {"class": null, "method": "_has_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "202"}, {"class": null, "method": "_has_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "174"}, {"class": null, "method": "_call_iter", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "307"}, {"class": null, "method": "_call_iter", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "279"}, {"class": null, "method": "<lambda>", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/reattach.py", "line": "175"}, {"class": null, "method": "__iter__", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/pyspark/sql/connect/client/core.py", "line": "658"}, {"class": null, "method": "__next__", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/grpc/_channel.py", "line": "543"}, {"class": null, "method": "_next", "file": "/Users/vik.malhotra/anaconda3/envs/azure_databricks/lib/python3.12/site-packages/grpc/_channel.py", "line": "969"}]}}
ERROR:SQLQueryContextLogger:[UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW] The feature is not supported: AI function ai_forecast is in preview and currently disabled in this environment. SQLSTATE: 0A000; line 2 pos 14

JVM stacktrace:
org.apache.spark.sql.AnalysisException
	at org.apache.spark.sql.errors.QueryCompilationErrors$.aiFunctionPreviewUnavailable(QueryCompilationErrors.scala:5310)
	at org.apache.spark.sql.execution.python.UserDefinedPythonTableFunction.builder(UserDefinedPythonFunction.scala:155)
	at com.databricks.sql.api.python.BuiltinPythonFunctions$.$anonfun$pythonTableFunction$1(BuiltinPythonFunctions.scala:71)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction(FunctionRegistry.scala:251)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction$(FunctionRegistry.scala:245)
	at org.apache.spark.sql.catalyst.analysis.SimpleTableFunctionRegistry.lookupFunction(FunctionRegistry.scala:1317)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.$anonfun$resolveBuiltinOrTempFunctionInternal$1(SessionCatalog.scala:3198)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.lookupTempFuncWithViewContext(SessionCatalog.scala:3209)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempFunctionInternal(SessionCatalog.scala:3198)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempTableFunction(SessionCatalog.scala:3185)
	at org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction(DelegatingSessionCatalog.scala:552)
	at org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction$(DelegatingSessionCatalog.scala:549)
	at com.databricks.sql.managedcatalog.ManagedCatalogSessionCatalog.resolveBuiltinOrTempTableFunction(ManagedCatalogSessionCatalog.scala:89)
	at org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveBuiltinOrTempTableFunction(FunctionResolution.scala:147)
	at org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveTableValuedFunction(FunctionResolution.scala:156)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.$anonfun$applyOrElse$173(Analyzer.scala:2783)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:107)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2780)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2757)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:141)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:85)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:141)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:42)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$2(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1330)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1329)
	at org.apache.spark.sql.catalyst.plans.logical.Project.mapChildren(basicLogicalOperators.scala:93)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)

AnalysisException: [UNSUPPORTED_FEATURE.AI_FUNCTION_PREVIEW] The feature is not supported: AI function ai_forecast is in preview and currently disabled in this environment. SQLSTATE: 0A000; line 2 pos 14

JVM stacktrace:
org.apache.spark.sql.AnalysisException
	at org.apache.spark.sql.errors.QueryCompilationErrors$.aiFunctionPreviewUnavailable(QueryCompilationErrors.scala:5310)
	at org.apache.spark.sql.execution.python.UserDefinedPythonTableFunction.builder(UserDefinedPythonFunction.scala:155)
	at com.databricks.sql.api.python.BuiltinPythonFunctions$.$anonfun$pythonTableFunction$1(BuiltinPythonFunctions.scala:71)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction(FunctionRegistry.scala:251)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistryBase.lookupFunction$(FunctionRegistry.scala:245)
	at org.apache.spark.sql.catalyst.analysis.SimpleTableFunctionRegistry.lookupFunction(FunctionRegistry.scala:1317)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.$anonfun$resolveBuiltinOrTempFunctionInternal$1(SessionCatalog.scala:3198)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.lookupTempFuncWithViewContext(SessionCatalog.scala:3209)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempFunctionInternal(SessionCatalog.scala:3198)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalogImpl.resolveBuiltinOrTempTableFunction(SessionCatalog.scala:3185)
	at org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction(DelegatingSessionCatalog.scala:552)
	at org.apache.spark.sql.catalyst.catalog.DelegatingSessionCatalog.resolveBuiltinOrTempTableFunction$(DelegatingSessionCatalog.scala:549)
	at com.databricks.sql.managedcatalog.ManagedCatalogSessionCatalog.resolveBuiltinOrTempTableFunction(ManagedCatalogSessionCatalog.scala:89)
	at org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveBuiltinOrTempTableFunction(FunctionResolution.scala:147)
	at org.apache.spark.sql.catalyst.analysis.FunctionResolution.resolveTableValuedFunction(FunctionResolution.scala:156)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.$anonfun$applyOrElse$173(Analyzer.scala:2783)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:107)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2780)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$21.applyOrElse(Analyzer.scala:2757)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$3(AnalysisHelper.scala:141)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:85)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:141)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:42)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$2(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1330)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1329)
	at org.apache.spark.sql.catalyst.plans.logical.Project.mapChildren(basicLogicalOperators.scala:93)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUpWithPruning$1(AnalysisHelper.scala:138)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning(AnalysisHelper.scala:137)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUpWithPruning$(AnalysisHelper.scala:133)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUpWithPruning(LogicalPlan.scala:42)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$.apply(Analyzer.scala:2757)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$.apply(Analyzer.scala:2752)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$16(RuleExecutor.scala:480)
	at org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule(RuleExecutor.scala:629)
	at org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule$(RuleExecutor.scala:613)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.processRule(RuleExecutor.scala:131)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$15(RuleExecutor.scala:480)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$14(RuleExecutor.scala:479)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$13(RuleExecutor.scala:475)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeBatch$1(RuleExecutor.scala:452)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$22(RuleExecutor.scala:585)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$22$adapted(RuleExecutor.scala:585)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:585)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:349)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeSameContext(Analyzer.scala:507)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:500)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:406)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:500)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:425)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:341)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:233)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:341)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:252)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:96)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:131)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:87)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:487)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:425)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:487)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$3(QueryExecution.scala:308)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:562)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$6(QueryExecution.scala:703)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:152)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:703)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1342)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:696)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:692)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:692)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:295)
	at com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:294)
	at scala.util.Try$.apply(Try.scala:210)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:340)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:274)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$3(Dataset.scala:149)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.SparkSession.$anonfun$withActiveAndFrameProfiler$1(SparkSession.scala:1470)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.SparkSession.withActiveAndFrameProfiler(SparkSession.scala:1470)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:141)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:1143)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:1095)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.executeSQL(SparkConnectPlanner.scala:3606)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleSqlCommand(SparkConnectPlanner.scala:3435)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3370)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:413)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:312)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:233)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:464)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1463)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:464)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:90)
	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:241)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:89)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:463)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:233)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:614)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)
	at scala.util.Using$.resource(Using.scala:261)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:614)

In [ ]:
-- Step 6: Forecast system health to predict failures
-- This uses AI_FORECAST to predict system health scores and identify at-risk systems

-- Run system health forecast
SELECT * FROM AI_FORECAST(
    TABLE(system_health_ts),
    horizon => DATE_ADD((SELECT MAX(date) FROM system_health_ts), 30),
    time_col => 'date',
    value_col => ARRAY('health_score', 'total_issues', 'critical_issues'),
    group_col => 'affected_systems',
    prediction_interval_width => 0.85,
    frequency => '1D',
    parameters => '{"global_floor": 0}'
)
ORDER BY affected_systems, date;

-- Identify systems at risk of failure (health_score_forecast > 5.0)
SELECT 
    affected_systems,
    date,
    health_score_forecast,
    health_score_upper,
    health_score_lower
FROM (
    SELECT * FROM AI_FORECAST(
        TABLE(system_health_ts),
        horizon => DATE_ADD((SELECT MAX(date) FROM system_health_ts), 30),
        time_col => 'date',
        value_col => ARRAY('health_score', 'total_issues', 'critical_issues'),
        group_col => 'affected_systems',
        prediction_interval_width => 0.85,
        frequency => '1D',
        parameters => '{"global_floor": 0}'
    )
)
WHERE health_score_forecast > 5.0
ORDER BY health_score_forecast DESC;

In [ ]:
-- Step 7: Create risk assessment and actionable recommendations
-- This analyzes forecast trends and provides maintenance recommendations

WITH system_health_forecast AS (
    SELECT * FROM AI_FORECAST(
        TABLE(system_health_ts),
        horizon => DATE_ADD((SELECT MAX(date) FROM system_health_ts), 30),
        time_col => 'date',
        value_col => ARRAY('health_score', 'total_issues', 'critical_issues'),
        group_col => 'affected_systems',
        prediction_interval_width => 0.85,
        frequency => '1D',
        parameters => '{"global_floor": 0}'
    )
),
forecast_summary AS (
    SELECT 
        affected_systems,
        AVG(health_score_forecast) as avg_predicted_health,
        MAX(health_score_forecast) as max_predicted_health,
        COUNT(*) as forecast_days
    FROM system_health_forecast
    GROUP BY affected_systems
),
risk_assessment AS (
    SELECT 
        affected_systems,
        avg_predicted_health,
        max_predicted_health,
        CASE 
            WHEN max_predicted_health > 8 THEN 'CRITICAL - Immediate attention required'
            WHEN max_predicted_health > 6 THEN 'HIGH - Schedule maintenance soon'
            WHEN max_predicted_health > 4 THEN 'MEDIUM - Monitor closely'
            ELSE 'LOW - Normal operation expected'
        END as risk_level,
        CASE 
            WHEN max_predicted_health > 8 THEN 'Schedule emergency maintenance within 48 hours'
            WHEN max_predicted_health > 6 THEN 'Plan maintenance within 1 week'
            WHEN max_predicted_health > 4 THEN 'Increase monitoring frequency'
            ELSE 'Continue normal monitoring'
        END as recommended_action
    FROM forecast_summary
)
SELECT * FROM risk_assessment
ORDER BY max_predicted_health DESC;

In [ ]:
-- Step 8: Save forecasting results to Unity Catalog
-- This creates permanent tables for dashboard integration

-- Save ticket volume forecast
CREATE OR REPLACE TABLE quickstart_catalog_vkm_external.classify_tickets.ticket_volume_forecast AS
SELECT * FROM AI_FORECAST(
    TABLE(ticket_volume_ts),
    horizon => DATE_ADD((SELECT MAX(date) FROM ticket_volume_ts), 30),
    time_col => 'date',
    value_col => ARRAY('total_tickets', 'high_urgency_tickets', 'critical_urgency_tickets'),
    prediction_interval_width => 0.95,
    frequency => '1D',
    parameters => '{"global_floor": 0}'
);

-- Save system health forecast
CREATE OR REPLACE TABLE quickstart_catalog_vkm_external.classify_tickets.system_health_forecast AS
SELECT * FROM AI_FORECAST(
    TABLE(system_health_ts),
    horizon => DATE_ADD((SELECT MAX(date) FROM system_health_ts), 30),
    time_col => 'date',
    value_col => ARRAY('health_score', 'total_issues', 'critical_issues'),
    group_col => 'affected_systems',
    prediction_interval_width => 0.85,
    frequency => '1D',
    parameters => '{"global_floor": 0}'
);

-- Save risk assessment insights
CREATE OR REPLACE TABLE quickstart_catalog_vkm_external.classify_tickets.risk_assessment_insights AS
WITH system_health_forecast AS (
    SELECT * FROM AI_FORECAST(
        TABLE(system_health_ts),
        horizon => DATE_ADD((SELECT MAX(date) FROM system_health_ts), 30),
        time_col => 'date',
        value_col => ARRAY('health_score', 'total_issues', 'critical_issues'),
        group_col => 'affected_systems',
        prediction_interval_width => 0.85,
        frequency => '1D',
        parameters => '{"global_floor": 0}'
    )
),
forecast_summary AS (
    SELECT 
        affected_systems,
        AVG(health_score_forecast) as avg_predicted_health,
        MAX(health_score_forecast) as max_predicted_health,
        COUNT(*) as forecast_days
    FROM system_health_forecast
    GROUP BY affected_systems
),
risk_assessment AS (
    SELECT 
        affected_systems,
        avg_predicted_health,
        max_predicted_health,
        CASE 
            WHEN max_predicted_health > 8 THEN 'CRITICAL - Immediate attention required'
            WHEN max_predicted_health > 6 THEN 'HIGH - Schedule maintenance soon'
            WHEN max_predicted_health > 4 THEN 'MEDIUM - Monitor closely'
            ELSE 'LOW - Normal operation expected'
        END as risk_level,
        CASE 
            WHEN max_predicted_health > 8 THEN 'Schedule emergency maintenance within 48 hours'
            WHEN max_predicted_health > 6 THEN 'Plan maintenance within 1 week'
            WHEN max_predicted_health > 4 THEN 'Increase monitoring frequency'
            ELSE 'Continue normal monitoring'
        END as recommended_action
    FROM forecast_summary
)
SELECT * FROM risk_assessment;

In [ ]:
-- Step 9: Verify saved tables and display summary
-- This confirms all forecasting tables were created successfully

-- Check ticket volume forecast table
SELECT 
    'ticket_volume_forecast' as table_name,
    COUNT(*) as record_count,
    MIN(date) as min_date,
    MAX(date) as max_date
FROM quickstart_catalog_vkm_external.classify_tickets.ticket_volume_forecast

UNION ALL

-- Check system health forecast table
SELECT 
    'system_health_forecast' as table_name,
    COUNT(*) as record_count,
    MIN(date) as min_date,
    MAX(date) as max_date
FROM quickstart_catalog_vkm_external.classify_tickets.system_health_forecast

UNION ALL

-- Check risk assessment insights table
SELECT 
    'risk_assessment_insights' as table_name,
    COUNT(*) as record_count,
    NULL as min_date,
    NULL as max_date
FROM quickstart_catalog_vkm_external.classify_tickets.risk_assessment_insights;

-- Display sample of risk assessment for immediate action
SELECT 
    affected_systems,
    risk_level,
    recommended_action,
    ROUND(max_predicted_health, 2) as max_health_score
FROM quickstart_catalog_vkm_external.classify_tickets.risk_assessment_insights
WHERE risk_level IN ('CRITICAL - Immediate attention required', 'HIGH - Schedule maintenance soon')
ORDER BY max_predicted_health DESC;

In [ ]:
# 🔮 AI FORECASTING SUMMARY

## ✅ Successfully implemented Databricks ai_forecast function

### 📈 Forecasting Capabilities:
- **Ticket volume prediction** (30-day horizon)
- **System health score prediction**
- **Asset failure risk assessment**
- **Proactive maintenance recommendations**

### 🎯 Key Features:
- **Prophet-like piecewise linear modeling**
- **Automatic seasonality detection**
- **95% prediction intervals**
- **Multi-metric and multi-group forecasting**
- **Built-in confidence intervals**

### 💡 Business Value:
- **Proactive issue prevention**
- **Resource planning optimization**
- **Reduced downtime and costs**
- **Data-driven maintenance scheduling**
- **Improved system reliability**

### 🚀 Next Steps:
- **Integrate forecasts into Streamlit dashboard**
- **Set up automated forecasting jobs**
- **Create alerting for high-risk predictions**
- **Implement real-time model retraining**

### 📊 Created Tables:
- `ticket_volume_forecast` - Daily ticket volume predictions
- `system_health_forecast` - System health score predictions
- `risk_assessment_insights` - Risk levels and recommendations

## 🎉 AI Forecasting implementation complete!